name: Deploy To OCI

on:
  push:
    branches:
      - feature/#29

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Github Repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup application.properties
        run: |
          rm -rf ./src/main/resources/application.properties
          rm -rf ./src/main/resources/application-dev.properties
          echo "${{ secrets.DEV_ROOT_APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
          echo "${{ secrets.DEV_APPLICATION_PROPERTIES }}" > ./src/main/resources/application-dev.properties

      - name: Gradle Build
        run: ./gradlew clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Release to Docker Hub
        run: |
          docker build -t ${{ vars.DOCKERHUB_REPOSITORY_NAME }}:development .
          docker tag ${{ vars.DOCKERHUB_REPOSITORY_NAME }}:development ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_NAME }}:development
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_NAME }}:development

      - name: Setup OCI Instance Public Key
        run: echo "${{ secrets.OCI_INSTANCE_PUBLIC_KEY }}" > ./oci_instance_ssh.key.pub

      - name: OCI Bastion Session Create
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          command: |
            bastion session create-managed-ssh
              --bastion-id ${{ secrets.OCI_BASTION_ID }}
              --display-name "GithubActionSession"
              --key-type PUB
              --ssh-public-key-file ./oci_instance_ssh.key.pub
              --target-resource-id ${{ secrets.OCI_INSTANCE_ID }}
              --target-os-username ubuntu
